name: 'Build and test Action'
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - run: npm run test:coverage

      - uses: codecov/codecov-action@v5

      - run: npm audit
